connect to ssh-agent before pushing secret changes

diff --git a/project/roles/ansible-runner/files/etc/webhook/hooks/put-secret b/project/roles/ansible-runner/files/etc/webhook/hooks/put-secret
--- a/project/roles/ansible-runner/files/etc/webhook/hooks/put-secret
+++ b/project/roles/ansible-runner/files/etc/webhook/hooks/put-secret
@@ -7,6 +7,24 @@ source /etc/ansible-runner/environment.sh
 # set default comment if one wasn't provided
 : "${COMMENT:=Update secret ${KEY} via webhook}"
 
+# Connect to the SSH agent. This SSH agent must have been previously started via `/usr/local/bin/unlock.sh`
+# The environment file should export 'SSH_AUTH_SOCK' and 'SSH_AGENT_PID'.
+if [ ! -f "$HOME/.ssh/environment" ]; then
+  echo "The ssh keys are not unlocked! Run /usr/local/bin/unlock.sh from a terminal."
+  echo "Aborting."
+  exit 1
+else
+  . "$HOME/.ssh/environment" > /dev/null
+  ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
+    rm "$HOME/.ssh/environment"
+    echo "The ssh-agent is no longer running. Run /usr/local/bin/unlock.sh from a terminal."
+    echo "Aborting."
+    exit 1
+  }
+fi
+
+source $HOME/.ssh/environment
+
 echo -n "${VALUE}" | /usr/local/bin/update-vault \
   "${VAULT_PATH}/vault.yml" \
   lab@/var/lib/ansible/vault-password \
